
import React from 'react';
import { 
  Syringe,
  MessageCircle,
  Bell,
  Info,
  Activity,
  Droplets,
  Thermometer,
  Wind,
  Waves,
  Eye,
  Bug,
  AlertCircle
} from 'lucide-react';
import { LanguageConfig } from './types';

export const LANGUAGES: LanguageConfig[] = [
  { code: 'en', name: 'English', nativeName: 'English' },
  { code: 'hi', name: 'Hindi', nativeName: 'हिन्दी' },
  { code: 'mr', name: 'Marathi', nativeName: 'मराఠी' },
  { code: 'bn', name: 'Bengali', nativeName: 'বাংলা' },
  { code: 'te', name: 'Telugu', nativeName: 'తెలుగు' }
];

export const UI_STRINGS = {
  en: {
    welcome: "Hello, I am JeevanSathi. I am here to help you stay healthy.",
    chooseLanguage: "Choose Language",
    typeMessage: "Type your health question...",
    send: "Send",
    disclaimer: "Note: For awareness only. Please consult a doctor.",
    emergency: "For medical emergencies, please call 108.",
    menu: "Menu",
    locationReady: "Location Ready",
    locationNotSet: "Location Not Set",
    vaxSchedule: "Immunization Schedule",
    vaxScheduleSub: "Keep your family safe with on-time vaccinations.",
    checkDueVax: "Check Due Vaccines",
    age: "Age",
    phcLocator: "PHC Locator",
    regionalAlerts: "Regional Alerts",
    regionalAlertsSub: "Stay aware of local health risks.",
    precautions: "Precautions",
    emergencySupport: "Emergency Support",
    reportAnalysis: "Report Analysis",
    reportAnalysisSub: "Upload a photo of your reports or symptoms.",
    howToUse: "How to use JeevanSathi",
    howToUseSub: "Your companion for health information.",
    viewHistory: "View Previous History",
    historyTitle: "Past Conversations",
    backToCurrent: "Back to Current Chat",
    noHistory: "No history for this language.",
    viewPastHistory: "View Past History",
    backToChat: "Back to Chat",
    loadPreviousChat: "Load Previous Chat",
    analysisMode: "Analysis Mode Active",
    askAI: "Ask JeevanSathi",
    vaxDetailPrompt: "Tell me more about the vaccine for ",
    alertDetailPrompt: "Tell me more about this alert: ",
    tabs: [
      { id: 'chat', label: 'Chat', icon: <MessageCircle className="w-5 h-5" /> },
      { id: 'vaccines', label: 'Vaccines', icon: <Syringe className="w-5 h-5" /> },
      { id: 'alerts', label: 'Alerts', icon: <Bell className="w-5 h-5" /> },
      { id: 'help', label: 'Help', icon: <Info className="w-5 h-5" /> }
    ],
    vaccineScheduleData: [
      { age: "Early Pregnancy", vaccines: "Td-1", info: "Tetanus and adult Diphtheria. First dose as soon as pregnancy is known." },
      { age: "4 Weeks after Td-1", vaccines: "Td-2", info: "Second dose of Tetanus-Diphtheria for full protection." },
      { age: "At Birth", vaccines: "BCG, OPV-0, Hep-B 0", info: "Protects against TB, Polio, and Hepatitis B." },
      { age: "6 Weeks", vaccines: "Pentavalent-1, OPV-1, Rota-1, fIPV-1, PCV-1", info: "Protection against 5 diseases, Polio, Diarrhea, and Pneumonia." },
      { age: "10 Weeks", vaccines: "Pentavalent-2, OPV-2, Rota-2", info: "Second dose of essential infant vaccines." },
      { age: "14 Weeks", vaccines: "Pentavalent-3, OPV-3, Rota-3, fIPV-2, PCV-2", info: "Completes the primary infant series." },
      { age: "9-12 Months", vaccines: "MR-1, JE-1, PCV-Booster, Vit-A", info: "Measles, Rubella, and Encephalitis protection plus Vitamin A." },
      { age: "16-24 Months", vaccines: "DPT-Booster-1, MR-2, OPV-Booster, JE-2", info: "Boosts long-term immunity." },
      { age: "5-6 Years", vaccines: "DPT-Booster-2", info: "Ensures continued protection." },
      { age: "10 Years", vaccines: "Td", info: "Tetanus-Diphtheria booster for adolescents." },
      { age: "16 Years", vaccines: "Td", info: "Ensures adult immunity against Tetanus." }
    ],
    quickQuestions: [
      "6-month-old vaccines?",
      "Dengue symptoms",
      "Pregnancy diet",
      "Malaria prevention",
      "Heatwave tips"
    ],
    alertsData: [
      { id: 1, title: 'Dengue Outbreak', desc: 'Seasonal spike in mosquito-borne cases.', severity: 'high', precautions: ['Use mosquito nets', 'Wear full sleeves', 'Remove stagnant water'], icon: <Bug className="w-5 h-5" /> },
      { id: 2, title: 'Malaria Risk', desc: 'Heavy rains increase risk of Malaria.', severity: 'high', precautions: ['Use repellent', 'Cover water tanks', 'Visit PHC if fever persists'], icon: <Activity className="w-5 h-5" /> },
      { id: 3, title: 'Severe Heatwave', desc: 'Temperature expected to cross 45°C.', severity: 'medium', precautions: ['Drink ORS/water', 'Stay indoors 12-4 PM', 'Wear light cotton'], icon: <Thermometer className="w-5 h-5" /> },
      { id: 4, title: 'Waterborne Alert', desc: 'Cholera cases reported due to contaminated water.', severity: 'high', precautions: ['Boil drinking water', 'Wash hands with soap', 'Eat fresh food'], icon: <Waves className="w-5 h-5" /> },
      { id: 5, title: 'Japanese Encephalitis', desc: 'Brain fever risk detected in rural areas.', severity: 'high', precautions: ['Protect children from mosquitoes', 'Ensure vaccination', 'Keep surroundings clean'], icon: <AlertCircle className="w-5 h-5" /> },
      { id: 6, title: 'Chikungunya Alert', desc: 'Joint pain cases rising after rains.', severity: 'medium', precautions: ['Avoid water accumulation', 'Use anti-mosquito creams', 'Rest and hydration'], icon: <Bug className="w-5 h-5" /> },
      { id: 7, title: 'Seasonal Flu', desc: 'Common cold and flu cases spreading.', severity: 'low', precautions: ['Wash hands often', 'Stay home if sick', 'Drink warm fluids'], icon: <Thermometer className="w-5 h-5" /> }
    ]
  },
  hi: {
    welcome: "नमस्ते, मैं जीवनसाथी हूँ। मैं आपको स्वस्थ रहने में मदद करने के लिए यहाँ हूँ।",
    chooseLanguage: "भाषा चुनें",
    typeMessage: "अपना स्वास्थ्य प्रश्न लिखें...",
    send: "भेजें",
    disclaimer: "नोट: केवल जागरूकता के लिए। डॉक्टर से सलाह लें।",
    emergency: "आपातकालीन स्थिति में 108 पर कॉल करें।",
    menu: "मेनू",
    locationReady: "स्थान तैयार है",
    locationNotSet: "स्थान सेट नहीं है",
    vaxSchedule: "टीकाकरण समय-सारणी",
    vaxScheduleSub: "समय पर टीकाकरण से अपने परिवार को सुरक्षित रखें।",
    checkDueVax: "टीकों की जाँच करें",
    age: "आयु",
    phcLocator: "PHC खोजें",
    regionalAlerts: "क्षेत्रीय अलर्ट",
    regionalAlertsSub: "स्थानीय स्वास्थ्य जोखिमों से अवगत रहें।",
    precautions: "सावधानियां",
    emergencySupport: "आपातकालीन सहायता",
    reportAnalysis: "रिपोर्ट विश्लेषण",
    reportAnalysisSub: "रिपोर्ट या लक्षणों की फोटो अपलोड करें।",
    howToUse: "उपयोग कैसे करें",
    howToUseSub: "स्वास्थ्य जानकारी के लिए आपका साथी।",
    viewHistory: "पिछला इतिहास देखें",
    historyTitle: "पिछली बातचीत",
    backToCurrent: "वर्तमान चैट पर वापस जाएं",
    noHistory: "इस भाषा के लिए कोई इतिहास नहीं है।",
    viewPastHistory: "पिछला इतिहास देखें",
    backToChat: "चैट पर वापस जाएं",
    loadPreviousChat: "पिछली चैट लोड करें",
    analysisMode: "विश्लेषण मोड सक्रिय",
    askAI: "जीवनसाथी से पूछें",
    vaxDetailPrompt: "मुझे इस टीके के बारे में और बताएं: ",
    alertDetailPrompt: "मुझे इस अलर्ट के बारे में और बताएं: ",
    tabs: [
      { id: 'chat', label: 'चैट', icon: <MessageCircle className="w-5 h-5" /> },
      { id: 'vaccines', label: 'टीके', icon: <Syringe className="w-5 h-5" /> },
      { id: 'alerts', label: 'अलर्ट', icon: <Bell className="w-5 h-5" /> },
      { id: 'help', label: 'मदद', icon: <Info className="w-5 h-5" /> }
    ],
    vaccineScheduleData: [
      { age: "गर्भावस्था की शुरुआत", vaccines: "Td-1", info: "टिटनेस और डिप्थीरिया। गर्भावस्था का पता चलते ही पहली खुराक।" },
      { age: "Td-1 के 4 सप्ताह बाद", vaccines: "Td-2", info: "पूर्ण सुरक्षा के लिए टिटनेस-डिप्थीरिया की दूसरी खुराक।" },
      { age: "जन्म के समय", vaccines: "BCG, OPV-0, Hep-B 0", info: "टीबी, पोलियो और हेपेाटाइटिस बी से बचाता है।" },
      { age: "6 सप्ताह", vaccines: "Pentavalent-1, OPV-1, Rota-1, fIPV-1, PCV-1", info: "5 रोगों, पोलियो, दस्त और निमोनिया से सुरक्षा।" },
      { age: "10 सप्ताह", vaccines: "Pentavalent-2, OPV-2, Rota-2", info: "शिशु टीकों की दूसरी खुराक।" },
      { age: "14 सप्ताह", vaccines: "Pentavalent-3, OPV-3, Rota-3, fIPV-2, PCV-2", info: "प्राथमिक शिशु टीकाकरण श्रृंखला को पूरा करता है।" },
      { age: "9-12 महीने", vaccines: "MR-1, JE-1, PCV-Booster, Vit-A", info: "खसरा, रूबेला और एन्सेफलाइटिस से सुरक्षा।" },
      { age: "16-24 महीने", vaccines: "DPT-Booster-1, MR-2, OPV-Booster, JE-2", info: "दीर्घकालिक प्रतिरक्षा बढ़ाता है।" },
      { age: "5-6 साल", vaccines: "DPT-Booster-2", info: "निरंतर सुरक्षा सुनिश्चित करता है।" },
      { age: "10 साल", vaccines: "Td", info: "किशोरों के लिए टिटनेस-डिप्थीरिया बूस्टर।" },
      { age: "16 साल", vaccines: "Td", info: "टिटनेस के खिलाफ वयस्क प्रतिरक्षा सुनिश्चित करता है।" }
    ],
    quickQuestions: [
      "6 महीने के बच्चे के टीके?",
      "डेंगू के लक्षण",
      "गर्भावस्था में आहार",
      "मलेरिया से बचाव",
      "गर्मी से बचाव के टिप्स"
    ],
    alertsData: [
      { id: 1, title: 'डेंगू का प्रकोप', desc: 'मच्छर जनित मामलों में मौसमी वृद्धि।', severity: 'high', precautions: ['मच्छरदानी का प्रयोग करें', 'पूरी आस्तीन के कपड़े पहनें', 'रुका हुआ पानी हटा दें'], icon: <Bug className="w-5 h-5" /> },
      { id: 2, title: 'मलेरिया का खतरा', desc: 'भारी बारिश से मलेरिया का खतरा बढ़ गया है।', severity: 'high', precautions: ['रिपेलेंट का उपयोग करें', 'पानी की टंकियों को ढकें', 'बुखार होने पर PHC जाएँ'], icon: <Activity className="w-5 h-5" /> },
      { id: 3, title: 'भीषण लू', desc: 'तापमान 45°C पार करने की संभावना।', severity: 'medium', precautions: ['ORS/पानी पिएं', 'दोपहर 12-4 बजे अंदर रहें', 'सूती कपड़े पहनें'], icon: <Thermometer className="w-5 h-5" /> },
      { id: 4, title: 'जलजनित रोग अलर्ट', desc: 'दूषित पानी के कारण हैजा के मामले सामने आए।', severity: 'high', precautions: ['पानी उबालकर पिएं', 'हाथ साबुन से धोएं', 'ताजा खाना खाएं'], icon: <Waves className="w-5 h-5" /> },
      { id: 5, title: 'जापानी एन्सेफलाइटिस', desc: 'ग्रामीण क्षेत्रों में दिमागी बुखार का खतरा।', severity: 'high', precautions: ['बच्चों को मच्छरों से बचाएं', 'टीकाकरण सुनिश्चित करें', 'आस-पास सफाई रखें'], icon: <AlertCircle className="w-5 h-5" /> },
      { id: 6, title: 'चिकनगुनिया अलर्ट', desc: 'बारिश के बाद जोड़ों के दर्द के मामले बढ़ रहे हैं।', severity: 'medium', precautions: ['पानी जमा न होने दें', 'एंटी-मच्छर क्रीम लगाएं', 'आराम और पानी पिएं'], icon: <Bug className="w-5 h-5" /> },
      { id: 7, title: 'मौसमी फ्लू', desc: 'सर्दी और फ्लू के मामले फैल रहे हैं।', severity: 'low', precautions: ['बार-बार हाथ धोएं', 'बीमार होने पर घर रहें', 'गर्म तरल पदार्थ पिएं'], icon: <Thermometer className="w-5 h-5" /> }
    ]
  },
  mr: {
    welcome: "नमस्कार, मी जीवनसाथी आहे. मी तुम्हाला निरोगी राहण्यास मदत करण्यासाठी येथे आहे.",
    chooseLanguage: "भाषा निवडा",
    typeMessage: "आरोग्य प्रश्न टाईप करा...",
    send: "पाठवा",
    disclaimer: "टीप: फक्त जागरूकतेसाठी. डॉक्टरांचा सल्ला घ्या.",
    emergency: "आणीबाणीसाठी 108 वर कॉल करा.",
    menu: "मेनू",
    locationReady: "स्थान तैयार आहे",
    locationNotSet: "स्थान सेट नाही",
    vaxSchedule: "लसीकरण वेळापत्रक",
    vaxScheduleSub: "वेळेवर लसीकरणासह कुटुंबाला सुरक्षित ठेवा.",
    checkDueVax: "लसी तपाసా",
    age: "वय",
    phcLocator: "PHC शोधक",
    regionalAlerts: "प्रादेशिक सतर्कता",
    regionalAlertsSub: "आरोग्य जोखीम बद्दल जागरूक रहा.",
    precautions: "सावधानता",
    emergencySupport: "आणीबाणी मदत",
    reportAnalysis: "अहवाल विश्लेषण",
    reportAnalysisSub: "अहवालाचा किंवा लक्षणांचा फोटो अपलोड करा.",
    howToUse: "कसे वापरावे",
    howToUseSub: "आरोग्य माहितीसाठी सोबती.",
    viewHistory: "जुना इतिहास पहा",
    historyTitle: "जुनी संभाषणे",
    backToCurrent: "सध्याच्या चॅटवर परत जा",
    noHistory: "या भाषेसाठी इतिहास नाही.",
    viewPastHistory: "जुना इतिहास पहा",
    backToChat: "चॅटवर परत जा",
    loadPreviousChat: "जुनी चॅट लोड करा",
    analysisMode: "विश्लेषण मोड सक्रिय",
    askAI: "जीवनसाथीला विचारा",
    vaxDetailPrompt: "मला या लसीबद्दल अधिक सांगा: ",
    alertDetailPrompt: "मला या अलर्टबद्दल अधिक सांगा: ",
    tabs: [
      { id: 'chat', label: 'चॅट', icon: <MessageCircle className="w-5 h-5" /> },
      { id: 'vaccines', label: 'लसी', icon: <Syringe className="w-5 h-5" /> },
      { id: 'alerts', label: 'सतर्कता', icon: <Bell className="w-5 h-5" /> },
      { id: 'help', label: 'मदत', icon: <Info className="w-5 h-5" /> }
    ],
    vaccineScheduleData: [
      { age: "गर्भधारणेच्या सुरुवातीस", vaccines: "Td-1", info: "धनुर्वात आणि प्रौढ घटसर्प. गर्भधारणा समजताच पहिला डोस." },
      { age: "Td-1 नंतर 4 आठवड्यांनी", vaccines: "Td-2", info: "पूर्ण संरक्षणासाठी धनुर्वात-घटसर्पचा दुसरा डोस." },
      { age: "जन्मतः", vaccines: "BCG, OPV-0, Hep-B 0", info: "टीबी, पोलिओ आणि हिपॅटायटीस बी पासून संरक्षण." },
      { age: "6 आठवडे", vaccines: "Pentavalent-1, OPV-1, Rota-1, fIPV-1, PCV-1", info: "5 आजार, पोलिओ, जुलाब आणि न्यूमोनियापासून संरक्षण." },
      { age: "10 आठवडे", vaccines: "Pentavalent-2, OPV-2, Rota-2", info: "लहान मुलांच्या लसींचा दुसरा डोस." },
      { age: "14 आठवडे", vaccines: "Pentavalent-3, OPV-3, Rota-3, fIPV-2, PCV-2", info: "प्राथमिक लसीकरण पूर्ण होते." },
      { age: "9-12 महिने", vaccines: "MR-1, JE-1, PCV-Booster, Vit-A", info: "गोवर, रुबेला आणि मेंदूज्वरापासून संरक्षण." },
      { age: "16-24 महिने", vaccines: "DPT-Booster-1, MR-2, OPV-Booster, JE-2", info: "दीर्घकालीन प्रतिकारशक्ती वाढवते." },
      { age: "5-6 वर्षे", vaccines: "DPT-Booster-2", info: "सतत संरक्षण सुनिश्चित करते." },
      { age: "10 वर्षे", vaccines: "Td", info: "किशोरवयीन मुलांसाठी धनुर्वात-घटसर्प बूस्टर." },
      { age: "16 वर्षे", vaccines: "Td", info: "प्रौढांमधील धनुर्वात प्रतिकारशक्ती सुनिश्चित करते." }
    ],
    quickQuestions: [
      "६ महिन्यांच्या बाळाच्या लसी?",
      "डेंग्यूची लक्षणे",
      "गरोदरपणातील आहार",
      "हिवताप प्रतिबंध",
      "उष्णतेच्या लाटेसाठी टिप्स"
    ],
    alertsData: [
      { id: 1, title: 'डेंग्यूचा प्रादुर्भाव', desc: 'डासांमुळे होणाऱ्या आजारांत वाढ.', severity: 'high', precautions: ['मच्छरदानी वापरा', 'पूर्ण कपडे वापरा', 'साचलेले पाणी काढा'], icon: <Bug className="w-5 h-5" /> },
      { id: 2, title: 'हिवताप धोका', desc: 'पावसामुळे हिवताపాचा धोका वाढला आहे.', severity: 'high', precautions: ['रिपेलेंट वापरा', 'पाण्याच्या टाक्या झाकून ठेवा', 'ताप आल्यास PHC ला भेट द्या'], icon: <Activity className="w-5 h-5" /> },
      { id: 3, title: 'प्रचंड उष्णतेची लाट', desc: 'तापमान 45°C ओलांडण्याची शक्यता.', severity: 'medium', precautions: ['ORS/पाणी प्या', 'दुपारी 12-4 बाहेर पडू नका', 'सुती कपडे वापरा'], icon: <Thermometer className="w-5 h-5" /> },
      { id: 4, title: 'पाण्यावाटे होणारे आजार', desc: 'दूषित पाण्यामुळे कॉलराचे रुग्ण आढळले.', severity: 'high', precautions: ['पाणी उकळून प्या', 'हात स्वच्छ धुवा', 'ताजे अन्न खा'], icon: <Waves className="w-5 h-5" /> },
      { id: 5, title: 'जपानी एनसेफलायटीस', desc: 'ग्रामीण भागात मेंदूज्वराचा धोका.', severity: 'high', precautions: ['मुलांचे डासांपासून संरक्षण करा', 'लसीकरण पूर्ण करा', 'परिसर स्वच्छ ठेवा'], icon: <AlertCircle className="w-5 h-5" /> },
      { id: 6, title: 'चिकनगुनिया सतर्कता', desc: 'पावसानंतर सांधेदुखीचे रुग्ण वाढत आहेत.', severity: 'medium', precautions: ['पानी साचू देऊ नका', 'डास प्रतिबंधक क्रीम वापरा', 'विश్రాंती आणि पाणी प्या'], icon: <Bug className="w-5 h-5" /> },
      { id: 7, title: 'हंगामी फ्लू', desc: 'सर्दी आणि फ्लूचा संसर्ग पसरत आहे.', severity: 'low', precautions: ['हात वारंवार धुवा', 'आजारी असल्यास घरी राहा', 'गरम पाणी प्या'], icon: <Thermometer className="w-5 h-5" /> }
    ]
  },
  bn: {
    welcome: "নমস্কার, আমি জীবনসাথী। আপনাকে সুস্থ থাকতে সাহায্য করার জন্য আমি এখানে আছি।",
    chooseLanguage: "ভাষা নির্বাচন করুন",
    typeMessage: "আপনার স্বাস্থ্য প্রশ্ন টাইপ করুন...",
    send: "পাঠান",
    disclaimer: "দ্রষ্টব্য: সচেতনতার জন্য। ডাক্তারের পরামর্শ নিন।",
    emergency: "জরুরী চিকিৎসার জন্য 108 নম্বরে কল করুন।",
    menu: "মেনু",
    locationReady: "অবস্থান প্রস্তুত",
    locationNotSet: "অবস্থান সেট করা নেই",
    vaxSchedule: "টিকাদান সূচী",
    vaxScheduleSub: "সময়মত টিকাদানের মাধ্যমে পরিবারকে নিরাপদ রাখুন।",
    checkDueVax: "টিকা পরীক্ষা করুন",
    age: "বয়স",
    phcLocator: "PHC সন্ধানকারী",
    regionalAlerts: "আঞ্চলিক সতর্কতা",
    regionalAlertsSub: "স্বাস্থ্য ঝুঁকি সম্পর্কে সচেতন থাকুন।",
    precautions: "সতর্কতা",
    emergencySupport: "জরুরী সহায়তা",
    reportAnalysis: "রিপোর্ট বিশ্লেষণ",
    reportAnalysisSub: "রিপোর্ট বা লক্ষণের ছবি আপলোড করুন।",
    howToUse: "কিভাবে ব্যবহার করবেন",
    howToUseSub: "স্বাস্থ্য তথ্যের জন্য আপনার সঙ্গী।",
    viewHistory: "পুরানো ইতিহাস দেখুন",
    historyTitle: "পুরানো কথোপকথন",
    backToCurrent: "বর্তমান চ্যাটে ফিরে যান",
    noHistory: "এই ভাষার জন্য কোনো ইতিহাস নেই।",
    viewPastHistory: "পুরানো ইতিহাস দেখুন",
    backToChat: "চ্যাটে ফিরে যান",
    loadPreviousChat: "পুরানো চ্যাট লোড করুন",
    analysisMode: "বিশ্লেষণ মোড সক্রিয়",
    askAI: "জীবনসাথীকে জিজ্ঞাসা করুন",
    vaxDetailPrompt: "এই টিকা সম্পর্কে আমাকে আরও বলুন: ",
    alertDetailPrompt: "এই সতর্কতা সম্পর্কে আমাকে আরও বলুন: ",
    tabs: [
      { id: 'chat', label: 'চ্যাট', icon: <MessageCircle className="w-5 h-5" /> },
      { id: 'vaccines', label: 'টিকা', icon: <Syringe className="w-5 h-5" /> },
      { id: 'alerts', label: 'সতর্কতা', icon: <Bell className="w-5 h-5" /> },
      { id: 'help', label: 'সাহায্য', icon: <Info className="w-5 h-5" /> }
    ],
    vaccineScheduleData: [
      { age: "গর্ভাবস্থার শুরুতে", vaccines: "Td-1", info: "টিটেনাস এবং ডিপিটি। গর্ভাবস্থা জানার সাথে সাথেই প্রথম ডোজ।" },
      { age: "Td-1 এর 4 সপ্তাহ পর", vaccines: "Td-2", info: "পূর্ণ সুরক্ষার জন্য টিটেনাস-ডিপিটি-র দ্বিতীয় ডোজ।" },
      { age: "জন্মের সময়", vaccines: "BCG, OPV-0, Hep-B 0", info: "টিবি, পোলিও এবং হেপাটাইটিস বি থেকে রক্ষা করে।" },
      { age: "6 সপ্তাহ", vaccines: "Pentavalent-1, OPV-1, Rota-1, fIPV-1, PCV-1", info: "5টি রোগ, পোলিও, ডায়রিয়া এবং নিউমোনিয়া থেকে সুরক্ষা।" },
      { age: "10 সপ্তাহ", vaccines: "Pentavalent-2, OPV-2, Rota-2", info: "শিশু টিকার দ্বিতীয় ডোজ।" },
      { age: "14 সপ্তাহ", vaccines: "Pentavalent-3, OPV-3, Rota-3, fIPV-2, PCV-2", info: "প্রাথমিক টিকাদান সম্পন্ন হয়।" },
      { age: "9-12 মাস", vaccines: "MR-1, JE-1, PCV-Booster, Vit-A", info: "হাম, রুবেলা এবং এনসেফালোপ্যাথি থেকে সুরক্ষা।" },
      { age: "16-24 মাস", vaccines: "DPT-Booster-1, MR-2, OPV-Booster, JE-2", info: "দীর্ঘমেয়াদী রোগ প্রতিরোধ ক্ষমতা বাড়ায়।" },
      { age: "5-6 বছর", vaccines: "DPT-Booster-2", info: "নিরবিচ্ছিন্ন সুরক্ষা নিশ্চিত করে।" },
      { age: "10 বছর", vaccines: "Td", info: "কিশোর-কিশোরীদের জন্য টিটেনাস-ডিপিটি বুস্টার।" },
      { age: "16 বছর", vaccines: "Td", info: "টিটেনাসের বিরুদ্ধে প্রাপ্তবয়স্কদের রোগ প্রতিরোধ ক্ষমতা নিশ্চিত করে।" }
    ],
    quickQuestions: [
      "৬ মাসের শিশুর টিকা?",
      "ডেঙ্গুর লক্ষণ",
      "গর্ভাবস্থায় ডায়েট",
      "ম্যালেরিয়া প্রতিরোধ",
      "তাপপ্রবাহের টিপস"
    ],
    alertsData: [
      { id: 1, title: 'ডেঙ্গুর প্রকোপ', desc: 'মশাবাহিত রোগের ঋতুভিত্তিক বৃদ্ধি।', severity: 'high', precautions: ['মশারি ব্যবহার করুন', 'পুরো হাতার পোশাক পরুন', 'জমে থাকা জল সরিয়ে ফেলুন'], icon: <Bug className="w-5 h-5" /> },
      { id: 2, title: 'ম্যালেরিয়ার ঝুঁকি', desc: 'ভারী বৃষ্টির ফলে ম্যালেরিয়ার প্রকোপ বেড়েছে।', severity: 'high', precautions: ['রিপেলেন্ট ব্যবহার করুন', 'জলের ট্যাঙ্ক ঢেকে রাখুন', 'জ্বর হলে PHC-তে যান'], icon: <Activity className="w-5 h-5" /> },
      { id: 3, title: 'তীব্র তাপপ্রবাহ', desc: 'তাপমাত্রা ৪৫ ডিগ্রি অতিক্রম করার সম্ভাবনা।', severity: 'medium', precautions: ['ORS/জল পান করুন', 'বেলা ১২-৪টা ভেতরে থাকুন', 'সুতির পোশাক পরুন'], icon: <Thermometer className="w-5 h-5" /> },
      { id: 4, title: 'জলবাহিত রোগ সতর্কতা', desc: 'দূষিত জলের কারণে কলেরার ঘটনা ঘটেছে।', severity: 'high', precautions: ['জল ফুটিয়ে পান করুন', 'সাবান দিয়ে হাত ধোয়ান', 'তাজা খাবার খান'], icon: <Waves className="w-5 h-5" /> },
      { id: 5, title: 'জাপানি এনসেফালাইটিস', desc: 'গ্রামীণ এলাকায় মস্তিষ্কের জ্বরের ঝুঁকি।', severity: 'high', precautions: ['শিশুদের মশা থেকে রক্ষা করুন', 'টিকাদান নিশ্চিত করুন', 'চারপাশ পরিষ্কার রাখুন'], icon: <AlertCircle className="w-5 h-5" /> },
      { id: 6, title: 'চিকুনগুনিয়া সতর্কতা', desc: 'বৃষ্টির পর গাঁটে ব্যথার রোগী বাড়ছে।', severity: 'medium', precautions: ['জল জমতে দেবেন না', 'মশা নিরোধক ক্রিম ব্যবহার করুন', 'বিশ্রাম ও জল পান করুন'], icon: <Bug className="w-5 h-5" /> },
      { id: 7, title: 'মরসুমী ফ্লু', desc: 'সর্দি ও ফ্লু ছড়িয়ে পড়ছে।', severity: 'low', precautions: ['ঘন ঘন হাত ধোয়ান', 'অসুস্থ হলে ঘরে থাকুন', 'গরম তরল খাবার খান'], icon: <Thermometer className="w-5 h-5" /> }
    ]
  },
  te: {
    welcome: "నమస్కారం, నేను జీవనసాథిని. మీకు సహాయం చేయడానికి ఇక్కడ ఉన్నాను.",
    chooseLanguage: "భాషను ఎంచుకోండి",
    typeMessage: "మీ ఆరోగ్య ప్రశ్నను టైప్ చేయండి...",
    send: "పంపండి",
    disclaimer: "గమనిక: అవగాహన కోసం మాత్రమే. వైద్యుడిని సంప్రదించండి.",
    emergency: "అత్యవసర పరిస్థితుల కోసం 108 కి కాల్ చేయండి.",
    menu: "మెనూ",
    locationReady: "స్థానం సిద్ధంగా ఉంది",
    locationNotSet: "స్థానం సెట్ చేయబడలేదు",
    vaxSchedule: "టీకాల షెడ్యూల్",
    vaxScheduleSub: "టీకాలు వేయించడం ద్వారా సురక్షితంగా ఉండండి.",
    checkDueVax: "టీకాలను తనిఖీ చేయండి",
    age: "వయస్సు",
    phcLocator: "PHC గుర్తింపు",
    regionalAlerts: "హెచ్చరికలు",
    regionalAlertsSub: "ఆరోగ్య ప్రమాదాల గురించి తెలుసుకోండి.",
    precautions: "ముందస్తు జాగ్రత్తలు",
    emergencySupport: "అత్యవసర మద్దతు",
    reportAnalysis: "రిపోర్ట్ విశ్లేషణ",
    reportAnalysisSub: "నివేదికలు లేదా లక్షణాల ఫోటోను అప్‌లోడ్ చేయండి.",
    howToUse: "ఎలా ఉపయోగించాలి",
    howToUseSub: "ఆరోగ్య సమాచారం కోసం తోడు.",
    viewHistory: "మునుపటి చరిత్రను చూడండి",
    historyTitle: "గత సంభాషణలు",
    backToCurrent: "ప్రస్తుత చాట్‌కు తిరిగి వెళ్ళు",
    noHistory: "ఈ భాషకు చరిత్ర లేదు.",
    viewPastHistory: "గత చరిత్రను చూడండి",
    backToChat: "చాట్‌కు తిరిగి వెళ్ళు",
    loadPreviousChat: "మునుపటి చాట్‌ను లోడ్ చేయండి",
    analysisMode: "విశ్లేషణ మోడ్ యాక్టివ్",
    askAI: "జీవనసాథిని అడగండి",
    vaxDetailPrompt: "ఈ టీకా గురించి నాకు మరిన్ని వివరాలు చెప్పండి: ",
    alertDetailPrompt: "ఈ హెచ్చరిక గురించి నాకు మరిన్ని వివరాలు చెప్పండి: ",
    tabs: [
      { id: 'chat', label: 'చాట్', icon: <MessageCircle className="w-5 h-5" /> },
      { id: 'vaccines', label: 'టీకాలు', icon: <Syringe className="w-5 h-5" /> },
      { id: 'alerts', label: 'హెచ్చరికలు', icon: <Bell className="w-5 h-5" /> },
      { id: 'help', label: 'సహాయం', icon: <Info className="w-5 h-5" /> }
    ],
    vaccineScheduleData: [
      { age: "గర్భధారణ ప్రారంభంలో", vaccines: "Td-1", info: "ధనుర్వాతం మరియు డిఫ్తీరియా. గర్భం దాల్చిన వెంటనే మొదటి డోస్." },
      { age: "Td-1 తర్వాత 4 వారాలకు", vaccines: "Td-2", info: "పూర్తి రక్షణ కోసం టీడీ రెండో డోస్." },
      { age: "పుట్టినప్పుడు", vaccines: "BCG, OPV-0, Hep-B 0", info: "టీబీ, పోలియో మరియు హెపటైటిస్ బి నుండి రక్షిస్తుంది." },
      { age: "6 వారాలు", vaccines: "Pentavalent-1, OPV-1, Rota-1, fIPV-1, PCV-1", info: "5 వ్యాధులు, పోలియో, విరేచనాలు మరియు న్యుమోనియా నుండి రక్షణ." },
      { age: "10 వారాలు", vaccines: "Pentavalent-2, OPV-2, Rota-2", info: "శిశు టీకాల రెండో డోస్." },
      { age: "14 వారాలు", vaccines: "Pentavalent-3, OPV-3, Rota-3, fIPV-2, PCV-2", info: "ప్రాథమిక టీకాల ప్రక్రియ పూర్తవుతుంది." },
      { age: "9-12 నెలలు", vaccines: "MR-1, JE-1, PCV-Booster, Vit-A", info: "తట్టు, రుబెల్లా మరియు మెదడువాపు వ్యాధి నుండి రక్షణ." },
      { age: "16-24 నెలలు", vaccines: "DPT-Booster-1, MR-2, OPV-Booster, JE-2", info: "దీర్ఘకాలిక రోగనిరోధక శక్తిని పెంచుతుంది." },
      { age: "5-6 సంవత్సరాలు", vaccines: "DPT-Booster-2", info: "నిరంతర రక్షణను నిర్ధారిస్తుంది." },
      { age: "10 సంవత్సరాలు", vaccines: "Td", info: "కిశోర ప్రాయం వారికి టీడీ బూస్టర్." },
      { age: "16 సంవత్సరాలు", vaccines: "Td", info: "పెద్దవారిలో ధనుర్వాత నిరోధక శక్తిని పెంచుతుంది." }
    ],
    quickQuestions: [
      "6 నెలల శిశువు టీకాలు?",
      "డెంగ్యూ లక్షణాలు",
      "గర్భధారణ ఆహారం",
      "మలేరియా నివారణ",
      "వడగాల్పుల చిట్కాలు"
    ],
    alertsData: [
      { id: 1, title: 'డెంగ్యూ వ్యాప్తి', desc: 'దోమల ద్వారా వ్యాపించే కేసుల పెరుగుదల.', severity: 'high', precautions: ['దోమతెరలు వాడండి', 'పూర్తి దుస్తులు ధరించండి', 'నిల్వ నీటిని తొలగించండి'], icon: <Bug className="w-5 h-5" /> },
      { id: 2, title: 'మలేరియా ముప్పు', desc: 'వర్షాల కారణంగా మలేరియా ముప్పు పెరిగింది.', severity: 'high', precautions: ['రిపెలెంట్ వాడండి', 'నీటి ట్యాంకులను మూసి ఉంచండి', 'జ్వరం వస్తే PHC కి వెళ్లండి'], icon: <Activity className="w-5 h-5" /> },
      { id: 3, title: 'తీవ్రమైన వడగాల్పులు', desc: 'ఉష్ణోగ్రత 45°C దాటే అవకాశం ఉంది.', severity: 'medium', precautions: ['ORS/నీరు త్రాగండి', 'మధ్యాహ్నం 12-4 మధ్య బయటకు వెళ్లకండి', 'పత్తి దుస్తులు ధరించండి'], icon: <Thermometer className="w-5 h-5" /> },
      { id: 4, title: 'నీటి ద్వారా వ్యాపించే వ్యాధులు', desc: 'కలుషిత నీటి వల్ల కలరా కేసులు నమోదయ్యాయి.', severity: 'high', precautions: ['నీటిని కాచి త్రాగండి', 'చేతులను సబ్బుతో కడగండి', 'తాజా ఆహారం తీసుకోండి'], icon: <Waves className="w-5 h-5" /> },
      { id: 5, title: 'మెదడు వాపు (JE)', desc: 'గ్రామీణ ప్రాంతాల్లో మెదడు వాపు వ్యాధి ముప్పు.', severity: 'high', precautions: ['పిల్లలను దోమల నుండి రక్షించండి', 'టీకాలు వేయించండి', 'పరిసరాలను శుభ్రంగా ఉంచండి'], icon: <AlertCircle className="w-5 h-5" /> },
      { id: 6, title: 'చికెన్ గున్యా హెచ్చరిక', desc: 'వర్షాల తర్వాత కీళ్ల నొప్పుల కేసులు పెరుగుతున్నాయి.', severity: 'medium', precautions: ['నీటి నిల్వను నివారించండి', 'దోమల నివారణ క్రీములు వాడండి', 'విశ్రాంతి మరియు నీరు తీసుకోండి'], icon: <Bug className="w-5 h-5" /> },
      { id: 7, title: 'కాలానుగుణ ఫ్లూ', desc: 'జలుబు మరియు ఫ్లూ కేసులు వ్యాప్తి చెందుతున్నాయి.', severity: 'low', precautions: ['తరచుగా చేతులు కడగండి', 'అనారోగ్యంగా ఉంటే ఇంట్లోనే ఉండండి', 'వేడి ద్రవాలు తీసుకోండి'], icon: <Thermometer className="w-5 h-5" /> }
    ]
  }
};
